services:
  pg:
    image: postgres:14.13-alpine3.20
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
volumes:
  pg-data:
    name: orders-postgres
